// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkH4UQ_Cjudq99BNcyb5HKhtlgORFgTSg',
    appId: '1:454938237717:web:fc7dd5d11af190c204671c',
    messagingSenderId: '454938237717',
    projectId: 'eco-14d93',
    authDomain: 'eco-14d93.firebaseapp.com',
    storageBucket: 'eco-14d93.appspot.com',
    measurementId: 'G-W66M461FGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT9yyBBDgYz-gnJ5YxbIjifgPjQMPKiRI',
    appId: '1:454938237717:android:5fc88d4c2de2997004671c',
    messagingSenderId: '454938237717',
    projectId: 'eco-14d93',
    storageBucket: 'eco-14d93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmUA3Mtw30IkCkvSqYZ7-yrUddUkEblH8',
    appId: '1:454938237717:ios:50a912b43fc7f5c004671c',
    messagingSenderId: '454938237717',
    projectId: 'eco-14d93',
    storageBucket: 'eco-14d93.appspot.com',
    iosBundleId: 'com.example.ecoGrow',
  );
}
