// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcq9t3IKzCLl99xuFlpRCG8Ufx1amXkM4',
    appId: '1:1081207055018:web:77f38077ec33218a94a6d3',
    messagingSenderId: '1081207055018',
    projectId: 'datnminh-787e2',
    authDomain: 'datnminh-787e2.firebaseapp.com',
    storageBucket: 'datnminh-787e2.appspot.com',
    measurementId: 'G-FS2DDBTQ7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGZVNYi7sqmRQTESzxwma3OJx2GMWeoRM',
    appId: '1:1081207055018:android:254014094e8930a094a6d3',
    messagingSenderId: '1081207055018',
    projectId: 'datnminh-787e2',
    storageBucket: 'datnminh-787e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDH_PFllJZDIWyN52ec0f0b_dGkim9UKk',
    appId: '1:1081207055018:ios:e6f6374450aa306994a6d3',
    messagingSenderId: '1081207055018',
    projectId: 'datnminh-787e2',
    storageBucket: 'datnminh-787e2.appspot.com',
    iosClientId: '1081207055018-v42jccefnfupt8rodpdvl5sqi9b49b2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoGrow',
  );
}
